# Generated by Django 3.1.3 on 2020-12-08 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Science', 'Science'), ('Maths', 'Maths'), ('Geometry', 'Geometry'), ('English', 'English'), ('History', 'History')], max_length=100)),
                ('name', models.CharField(max_length=70)),
                ('shortcut', models.CharField(max_length=15, unique=True)),
            ],
        ),
    ]
