# Generated by Django 3.1.3 on 2020-12-26 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downloaditemsample',
            name='photo',
        ),
    ]
