# Generated by Django 3.1.3 on 2021-02-25 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_ui', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatWeOfferCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '4.1. What we offer Category',
            },
        ),
        migrations.CreateModel(
            name='WhatWeOfferSubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to='whatweoffer/')),
                ('summary', models.TextField(max_length=2000)),
                ('status', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='custom_ui.whatweoffercategory')),
            ],
            options={
                'verbose_name': '4.2. What we offer Sub-Category',
            },
        ),
    ]
