# Generated by Django 3.1.3 on 2021-02-25 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_ui', '0002_whatweoffercategory_whatweoffersubcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='whatweoffercategory',
            options={},
        ),
        migrations.AlterModelOptions(
            name='whatweoffersubcategory',
            options={},
        ),
    ]
