# Generated by Django 3.1.3 on 2021-02-25 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_ui', '0003_auto_20210225_1242'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='whatweoffercategory',
            options={'verbose_name': '4.1. What we offer Category'},
        ),
        migrations.AlterModelOptions(
            name='whatweoffersubcategory',
            options={'verbose_name': '4.2. What we offer Sub-Category'},
        ),
    ]
