# Generated by Django 3.1.5 on 2021-02-20 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0003_auto_20210220_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='items',
            field=models.CharField(choices=[('book', 'book'), ('pen', 'pen'), ('folder', 'folder'), ('bag', 'bag')], max_length=20),
        ),
    ]
