# Generated by Django 3.1.3 on 2020-12-28 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
