# Generated by Django 3.1.3 on 2020-12-28 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, unique=True)),
                ('content', models.TextField()),
            ],
        ),
    ]
