# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 19:12
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import feedback.models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_auto_20170813_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='email',
            field=models.CharField(max_length=150, validators=[django.core.validators.EmailValidator(), django.core.validators.MinLengthValidator(7), django.core.validators.MaxLengthValidator(100), feedback.models.validate_allowed_domains]),
        ),
    ]
