# Generated by Django 3.1.3 on 2020-12-20 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amazonecustomer',
            name='manufacturer',
        ),
        migrations.AddField(
            model_name='amazonecustomer',
            name='available',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='amazonecustomer',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
