# Generated by Django 3.1.3 on 2020-12-20 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csvs', '0004_amazonecustomer_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amazone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amazonecustomer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csvs.amazonecustomer')),
            ],
        ),
    ]
