# Generated by Django 3.1.3 on 2020-12-21 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvs', '0005_amazone'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonecustomer',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
