# Generated by Django 3.1.3 on 2020-12-29 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('code', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30, unique=True)),
                ('duration', models.IntegerField()),
                ('fee', models.IntegerField()),
            ],
        ),
    ]
